// Copyright 2021 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Author: Florian Zaruba <zarubaf@iis.ee.ethz.ch>

// AUTOMATICALLY GENERATED by genoccamy.py; edit the script instead.

module ${name}_cva6 import ${name}_pkg::*; (
  input  logic              clk_i,
  input  logic              rst_ni,
  input  logic [1:0]        irq_i,
  input  logic              ipi_i,
  input  logic              time_irq_i,
  input  logic              debug_req_i,
  output ${soc_narrow_xbar.in_cva6.req_type()} axi_req_o,
  input  ${soc_narrow_xbar.in_cva6.rsp_type()} axi_resp_i,
  input  sram_cfg_cva6_t    sram_cfg_i
);

  <% cva6 = soc_narrow_xbar.in_cva6.copy(name="cva6_axi").declare(context).cut(context) %>

  assign axi_req_o = cva6_axi_cut_req;
  assign cva6_axi_cut_rsp = axi_resp_i;

  // TODO(zarubaf): Derive from system parameters
  localparam ariane_pkg::ariane_cfg_t CVA6OccamyConfig = '{
    RASDepth: 2,
    BTBEntries: 32,
    BHTEntries: 128,
    // DRAM -- SPM, SPM -- Boot ROM, Boot ROM -- Debug Module
    NrNonIdempotentRules: 3,
    NonIdempotentAddrBase: {64'd${cfg["spm_narrow"]["address"]+cfg["spm_narrow"]["length"]}           , 64'd${cfg["peripherals"]["rom"]["address"]+cfg["peripherals"]["rom"]["length"]}                      , 64'h1000},
    NonIdempotentLength:   {64'd${0x80000000-cfg["spm_narrow"]["address"]-cfg["spm_narrow"]["length"]}, 64'd${cfg["spm_narrow"]["address"]-cfg["peripherals"]["rom"]["address"]-cfg["peripherals"]["rom"]["length"]}, 64'd${cfg["peripherals"]["rom"]["address"]-0x1000}},
    NrExecuteRegionRules: 5,
    // DRAM, Boot ROM, SPM, Debug Module
    ExecuteRegionAddrBase: {64'h10_0000_0000, 64'h8000_0000, 64'd${cfg["peripherals"]["rom"]["address"]}, 64'd${cfg["spm_narrow"]["address"]}, 64'h0   },
    ExecuteRegionLength:   {64'h2_0000_0000 , 64'h8000_0000, 64'd${cfg["peripherals"]["rom"]["length"]} , 64'd${cfg["spm_narrow"]["length"]} , 64'h1000},
    // cached region
    NrCachedRegionRules:    2,
    CachedRegionAddrBase:  {64'h8000_0000, 64'd${cfg["spm_narrow"]["address"]}},
    CachedRegionLength:    {(64'hff_ffff_ffff-64'h8000_0000), 64'd${cfg["spm_narrow"]["length"]}},
    //  cache config
    AxiCompliant:           1'b1,
    SwapEndianess:          1'b0,
    // debug
    DmBaseAddress:          64'h0,
    NrPMPEntries:           8
  };

  logic [1:0]        irq;
  logic              ipi;
  logic              time_irq;
  logic              debug_req;

  sync #(.STAGES (2))
    i_sync_debug (.clk_i, .rst_ni, .serial_i (debug_req_i), .serial_o (debug_req));
  sync #(.STAGES (2))
    i_sync_ipi  (.clk_i, .rst_ni, .serial_i (ipi_i), .serial_o (ipi));
  sync #(.STAGES (2))
    i_sync_time_irq  (.clk_i, .rst_ni, .serial_i (time_irq_i), .serial_o (time_irq));
  sync #(.STAGES (2))
    i_sync_irq_0  (.clk_i, .rst_ni, .serial_i (irq_i[0]), .serial_o (irq[0]));
  sync #(.STAGES (2))
    i_sync_irq_1  (.clk_i, .rst_ni, .serial_i (irq_i[1]), .serial_o (irq[1]));

  localparam logic [63:0] BootAddr = 'd${cfg["peripherals"]["rom"]["address"]};

  // between tracing modules singals
  // TIP out - TE in
  logic [CVA6OccamyConfig.RASDepth-1:0]                                  tip_valid;
  logic [CVA6OccamyConfig.RASDepth-1:0][connector_pkg::IRETIRE_LEN-1:0]  iretire;
  logic [CVA6OccamyConfig.RASDepth-1:0]                                  ilastsize;
  logic [CVA6OccamyConfig.RASDepth-1:0][connector_pkg::ITYPE_LEN-1:0]    itype;
  logic [connector_pkg::XLEN-1:0]                                        cause;
  logic [connector_pkg::XLEN-1:0]                                        tval;
  logic [connector_pkg::PRIV_LEN-1:0]                                    priv;
  logic [CVA6OccamyConfig.RASDepth-1:0][connector_pkg::XLEN-1:0]         iaddr;

  // TE out - encapsulator in
  logic                           te_valid;
  te_pkg::it_packet_type_e        packet_type;
  logic [te_pkg::P_LEN-1:0]       packet_length;
  logic [te_pkg::PAYLOAD_LEN-1:0] packet_payload;

  // encapsulator out
  logic encap_ready;
  logic encap_valid;

  ariane #(
    .ArianeCfg (CVA6OccamyConfig),
    .AxiAddrWidth (${soc_narrow_xbar.in_cva6.aw}),
    .AxiDataWidth (${soc_narrow_xbar.in_cva6.dw}),
    .AxiIdWidth (${soc_narrow_xbar.in_cva6.iw}),
    .AxiUserWidth (${max(1, soc_narrow_xbar.in_cva6.uw)}),
    .axi_ar_chan_t(${soc_narrow_xbar.in_cva6.ar_chan_type()}),
    .axi_aw_chan_t(${soc_narrow_xbar.in_cva6.aw_chan_type()}),
    .axi_w_chan_t(${soc_narrow_xbar.in_cva6.w_chan_type()}),
    .axi_req_t (${soc_narrow_xbar.in_cva6.req_type()}),
    .axi_rsp_t (${soc_narrow_xbar.in_cva6.rsp_type()}),
    .sram_cfg_t (sram_cfg_t)
  ) i_cva6 (
    .clk_i,
    .rst_ni,
    .boot_addr_i (BootAddr),
    .hart_id_i (64'h0),
    .irq_i (irq),
    .ipi_i (ipi),
    .time_irq_i (time_irq),
    .debug_req_i (debug_req),
    .axi_req_o (cva6_axi_req),
    .axi_resp_i (cva6_axi_rsp),
    .sram_cfg_idata_i (sram_cfg_i.icache_data),
    .sram_cfg_itag_i (sram_cfg_i.icache_tag),
    .sram_cfg_ddata_i (sram_cfg_i.dcache_data),
    .sram_cfg_dtag_i (sram_cfg_i.dcache_tag),
    .sram_cfg_dvalid_dirty_i (sram_cfg_i.dcache_valid_dirty)
  );

  // TIP instance
      (* DONT_TOUCH = "TRUE" *) cva6_te_connector #(
        .NRET(2), // commit ports
        .N(2),  // special instruction
        .FIFO_DEPTH(8)
      ) i_cva6_tip (
        .clk_i,
        .rst_ni,
        .valid_i        ({i_cva6.commit_stage_i.commit_ack_o[1], i_cva6.commit_stage_i.commit_ack_o[0]}),
        .pc_i           ({i_cva6.commit_stage_i.commit_instr_i[1].pc, i_cva6.commit_stage_i.commit_instr_i[0].pc}),
        .op_i           ({i_cva6.commit_stage_i.commit_instr_i[1].op, i_cva6.commit_stage_i.commit_instr_i[0].op}),
        .is_compressed_i({i_cva6.commit_stage_i.commit_instr_i[1].is_compressed, i_cva6.commit_stage_i.commit_instr_i[0].is_compressed}),
        .branch_valid_i (i_cva6.resolved_branch.valid),
        .is_taken_i     (i_cva6.resolved_branch.is_taken),
        .cf_type_i      (i_cva6.resolved_branch.cf_type),
        .disc_pc_i      (i_cva6.resolved_branch.pc),
        .ex_valid_i     (i_cva6.commit_stage_i.exception_o.valid),
        .tval_i         (i_cva6.commit_stage_i.exception_o.tval),
        .cause_i        (i_cva6.commit_stage_i.exception_o.cause),
        .priv_lvl_i     (i_cva6.priv_lvl),
        .valid_o        (tip_valid),
        .iretire_o      (iretire),
        .ilastsize_o    (ilastsize),
        .itype_o        (itype),
        .cause_o        (cause),
        .tval_o         (tval),
        .priv_o         (priv),
        .iaddr_o        (iaddr)
      );

      // TE instance
      // TODO: hardwire te_reg signals
      // because I can't use APB to write
      (* DONT_TOUCH = "TRUE" *) trace_encoder #(
        .N(2), // is it 1?
        .ONLY_BRANCHES(1)
      ) i_TE (
        .clk_i,
        .rst_ni,
        .valid_i             (tip_valid),
        .itype_i             (itype),
        .cause_i             (cause),
        .tval_i              (tval),
        .priv_i              (priv),
        .iaddr_i             (iaddr),
        .iretire_i           (iretire),
        .ilastsize_i         (ilastsize),
        .time_i              ('0),
        .tvec_i              ('0),
        .epc_i               ('0),
        .encapsulator_ready_i(encap_ready),
        .paddr_i             ('0),
        .pwrite_i            ('0),
        .psel_i              ('0),
        .penable_i           ('0),
        .pwdata_i            ('0),
        .packet_valid_o      (te_valid),
        .packet_type_o       (packet_type),
        .packet_length_o     (packet_length),
        .packet_payload_o    (packet_payload),
        .stall_o             (), // not connected
        .pready_o            (), // not connected
        .prdata_o            () // not connected
      );

      // encapsulator_ATB instance
      (* DONT_TOUCH = "TRUE" *) encapsulator_atb #(
        .FIFO_DEPTH(4)
      ) i_encapsulator_atb (
        .clk_i,
        .rst_ni,
        .valid_i             (te_valid),
        .packet_length_i     (packet_length),
        .notime_i            (i_TE.notime),
        .timestamp_i         ('0), // understand where to read the csr value
        .trace_payload_i     (packet_payload),
        .atready_i           ('1), // always ready: check if it breaks something
        .afvalid_i           ('0),
        .atbytes_o           (), // not connected
        .atdata_o            (), // not connected
        .atid_o              (), // not connected
        .atvalid_o           (), // not connected
        .afready_o           (), // not connected
        .encapsulator_ready_o(encap_ready)
      );


endmodule
